baseURL = 'https://www.arhohuttunen.com/'
languageCode = 'en-us'
title = 'Code With Arho'
theme = 'codewitharho'
enableEmoji = true
enableGitInfo = true
ignoreFiles = [
  "\\.obsidian",
  "\\.excalidraw\\.md$"
]

[markup.highlight]
    style = "monokailight"
    noClasses = false

[build]
  [build.buildStats]
    enable = true
  [[build.cachebusters]]
    source = 'assets/notwatching/hugo_stats\.json'
    target = 'css'
  [[build.cachebusters]]
    source = '(postcss|tailwind)\.config\.js'
    target = 'css'
[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    disableWatch = true
    source = 'hugo_stats.json'
    target = 'assets/notwatching/hugo_stats.json'

[permalinks]
  posts = "/:slugorcontentbasename"

[params]
  [params.giscus]
    repo = "arhohuttunen/arhohuttunen.com"
    repo_id = "MDEwOlJlcG9zaXRvcnkzMTQ3OTgyMzk"
    category = "Blog"
    category_id = "DIC_kwDOEsNwn84CPtYU"
