[build]
  command = "npm run build"
  publish = "public"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"

[build.environment]
  HUGO_VERSION = "0.155.3"
  HUGO_ENVIRONMENT = "production"
  NODE_VERSION = "22"
